### ISSUE TITLE
顶栏丢失

### ISSUE THREAD

**Issue by Cao0220** [nyancatda/mcserverweb#1]
在大部分手机的浏览器中顶栏丢失。

**Comment by nyancatda** [comment]
我在iOS14和安卓9.0的设备上都进行了测试，并未成功复现问题，请提供具体设备型号，使用的浏览器等信息

**Comment by Cao0220** [comment]
in MI8 & MI10 & HUAWEI Mate 30（自带浏览器&QQ内置浏览器），edge&chrome（F12） 顶栏均失效。
![屏幕截图 2021-04-04 182518](https://user-images.githubusercontent.com/65110919/113505698-289baa00-9573-11eb-9c60-55caba51d0aa.png)

**Comment by nyancatda** [comment]
使用Edge浏览器和QQ内置浏览器均未复现成功，请确认本地配置是否正确
![1](https://user-images.githubusercontent.com/63787593/113505826-d313cd00-9573-11eb-88d1-7bf854f641f3.png)
![2](https://user-images.githubusercontent.com/63787593/113505830-d7d88100-9573-11eb-9e66-c94cc7f11ccd.PNG)

**Comment by nyancatda** [comment]
长时间未回复，已关闭issues
