### ISSUE TITLE
Rumao 

### ISSUE THREAD

**Issue by lixworth** [nyancatda/mcserverweb#2]
我来水issue了

* 一键启动脚本执行之后 在命令行回车 全部页面将会404
* 重复引入bootstrap
https://github.com/nyancatda/mcserverweb/blob/ac26837d16f962f324df52d0b17661fffeec9434/index.php#L19
https://github.com/nyancatda/mcserverweb/blob/ac26837d16f962f324df52d0b17661fffeec9434/index.php#L20

* 此处使用了bootstrap v3内置的图标库 glyphicon 
https://github.com/nyancatda/mcserverweb/blob/ac26837d16f962f324df52d0b17661fffeec9434/index.php#L42
但是再此处又引入了font-awesome 没有任何意义 并且awsomefont这个库的图标字体文件没有包含在项目中
https://github.com/nyancatda/mcserverweb/blob/ac26837d16f962f324df52d0b17661fffeec9434/index.php#L22
https://github.com/nyancatda/mcserverweb/blob/ac26837d16f962f324df52d0b17661fffeec9434/css/font-awesome.css#L9

* 使用creative-tim模板 并没有著名版权 2333
* 关于issue #1 
猜测是其网络环境无法从jsdelivr获取到bootstrap 从而走本地 而本地也没有储存bootstrap内置图标库glyphicon 的font文件
`    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">`
 而本地也没有储存bootstrap内置图标库glyphicon 的font文件
https://github.com/nyancatda/mcserverweb/blob/ac26837d16f962f324df52d0b17661fffeec9434/css/bootstrap.css#L2637

![image](https://user-images.githubusercontent.com/22554300/114405619-72226f80-9bd9-11eb-904d-2705f6ab7317.png)

**Comment by nyancatda** [comment]
感谢您的反馈！
***
以下是关于问题的回复:
1.一键启动程序为了保证临时文件的正常调用，故在最后保留了文件调用命令防止临时文件被清理，回车会触发调用文件命令执行，执行完毕后临时文件会被清除
2.已在[commit c0dc69a](https://github.com/nyancatda/mcserverweb/commit/c0dc69a928e38d4e4423a8c7aecd7ac9c899b018)中修复
3.已在[commit c0dc69a](https://github.com/nyancatda/mcserverweb/commit/c0dc69a928e38d4e4423a8c7aecd7ac9c899b018)中修复
4.根据其开源协议，无需标注出处
***
感谢您对项目支持!

**Comment by nyancatda** [comment]
长时间未回复，已关闭
