### ISSUE TITLE
基岩版官服 1.17.1.01无法读取正确的服务器状态

### ISSUE THREAD

**Issue by Luochancy** [nyancatda/mcserverweb#5]
网站和游戏挂在不同服务器上，网页无法显示正确的状态。已经确定服务器有开，配置文件也有改

**Comment by nyancatda** [comment]
请提供服务器IP地址和端口，方便我进行排查

**Comment by Luochancy** [comment]
lingkong.yunfeng.ink
19132

**Comment by Hacker-yfs** [comment]
lingkong.yunfeng.ink
19132

**Comment by Luochancy** [comment]
游戏端也显示不出来服务器状态，但服务器有开

**Comment by nyancatda** [comment]
![image](https://user-images.githubusercontent.com/63787593/127093129-b2fa2b5b-4a3a-4ea2-8981-283c3537d6e1.png)
请确认服务器信息是否正确，API确实是获取不到服务器信息

**Comment by Luochancy** [comment]
那我重新安装客户端试试

**Comment by nyancatda** [comment]
由于长时间未回复，已关闭该issues
